### ISSUE TITLE
Location List ",NY" or ",New York" issue

### ISSUE THREAD

**Issue by tans2** [InspectorRestaurant/ir_web_client#23]
<img width="156" alt="screen shot 2018-04-24 at 7 10 48 pm" src="https://user-images.githubusercontent.com/18352433/39219083-72495aee-47f6-11e8-8e8e-2e9c6bde366f.png">
<img width="175" alt="screen shot 2018-04-24 at 7 18 05 pm" src="https://user-images.githubusercontent.com/18352433/39219085-72568408-47f6-11e8-9194-cbdc06edf1e0.png">
<img width="148" alt="screen shot 2018-04-24 at 7 19 35 pm" src="https://user-images.githubusercontent.com/18352433/39219086-7266d5d8-47f6-11e8-97ca-d4ce08fd6559.png">
<img width="214" alt="screen shot 2018-04-24 at 7 20 19 pm" src="https://user-images.githubusercontent.com/18352433/39219087-72747e54-47f6-11e8-9faa-b147725ac99d.png">
<img width="200" alt="screen shot 2018-04-24 at 7 21 30 pm" src="https://user-images.githubusercontent.com/18352433/39219088-728a7b46-47f6-11e8-9e70-9f1298ed9815.png">
<img width="184" alt="screen shot 2018-04-24 at 7 24 20 pm" src="https://user-images.githubusercontent.com/18352433/39219089-729db210-47f6-11e8-9b08-def3890e2951.png">
<img width="170" alt="screen shot 2018-04-24 at 7 24 28 pm" src="https://user-images.githubusercontent.com/18352433/39219090-72b0ad70-47f6-11e8-8632-efcb30a3650e.png">

**Comment by aeksco** [comment]
Resolved
