### ISSUE TITLE
Location List Punctuation Issues (causing duplicate listings)

### ISSUE THREAD

**Issue by tans2** [InspectorRestaurant/ir_web_client#25]
<img width="185" alt="screen shot 2018-04-24 at 7 11 30 pm" src="https://user-images.githubusercontent.com/18352433/39219125-ab6e99ce-47f6-11e8-9d6d-68661f380161.png">
<img width="169" alt="screen shot 2018-04-24 at 7 14 11 pm" src="https://user-images.githubusercontent.com/18352433/39219126-ab7cd03e-47f6-11e8-9d48-545e67b2f5ad.png">
<img width="164" alt="screen shot 2018-04-24 at 7 15 57 pm" src="https://user-images.githubusercontent.com/18352433/39219127-ab899c10-47f6-11e8-9e93-de7e73c65367.png">
<img width="197" alt="screen shot 2018-04-24 at 7 16 57 pm" src="https://user-images.githubusercontent.com/18352433/39219128-ab977fc4-47f6-11e8-9fc7-60b152f27d21.png">
<img width="161" alt="screen shot 2018-04-24 at 7 17 26 pm" src="https://user-images.githubusercontent.com/18352433/39219129-aba6e98c-47f6-11e8-9190-b44564a4c4c7.png">
<img width="160" alt="screen shot 2018-04-24 at 7 23 17 pm" src="https://user-images.githubusercontent.com/18352433/39219130-abba0170-47f6-11e8-9363-68aa0f63ea2e.png">
<img width="141" alt="screen shot 2018-04-24 at 7 23 35 pm" src="https://user-images.githubusercontent.com/18352433/39219131-abc98460-47f6-11e8-9f31-06bd3204d969.png">
<img width="244" alt="screen shot 2018-04-24 at 7 24 06 pm" src="https://user-images.githubusercontent.com/18352433/39219132-abd6017c-47f6-11e8-813b-5da6c3cdf24d.png">

**Comment by aeksco** [comment]
Resolved
